<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-27T03:55:27Z" name="Suite" finished-at="2023-01-27T03:55:34Z" duration-ms="7367">
    <groups>
    </groups>
    <test started-at="2023-01-27T03:55:27Z" name="Test" finished-at="2023-01-27T03:55:34Z" duration-ms="7367">
      <class name="Test.loginTest">
        <test-method is-config="true" signature="main()[pri:0, instance:Test.loginTest@65ec8b24]" started-at="2023-01-27T03:55:21Z" name="main" finished-at="2023-01-27T03:55:27Z" duration-ms="6130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method signature="login()[pri:0, instance:Test.loginTest@65ec8b24]" started-at="2023-01-27T03:55:27Z" name="login" finished-at="2023-01-27T03:55:27Z" duration-ms="538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- Test.loginTest -->
      <class name="Test.materialTest">
        <test-method signature="Page()[pri:0, instance:Test.materialTest@3f49e266]" started-at="2023-01-27T03:55:27Z" name="Page" finished-at="2023-01-27T03:55:34Z" duration-ms="6767" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [1px] but found [14px]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1px] but found [14px]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Test.materialTest.Page(materialTest.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Page -->
      </class> <!-- Test.materialTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
